### ISSUE TITLE
Need help. How was it built?

### ISSUE THREAD

**Issue by akhilesh-k** [pulsejet/iitb-templates#1]
I was thinking to bootstrap from this project. How have you built it?

Are some script files missing?

**Comment by Shivansh2407** [comment]
Yes I also do think so that some files are missing.Can I complete this project if you need

**Comment by pulsejet** [comment]
Hi @akhilesh-k @Shivansh2407 
There are no script files as such; since building layouts change (very) rarely, this was built by hand, with just copy-paste. Actually, this repo is meant to serve a very specific purpose, as a submodule of [ferrous-client](https://github.com/pulsejet/ferrous-client/), which in turn is a submodule of [ferrous](https://github.com/pulsejet/ferrous/), so I don't know how useful the code in here might be.

**Comment by akhilesh-k** [comment]
Got it. Thanks!
